### PR TITLE
chore: Change to LGPL-3.0 license

### LINKED ISSUE #32: [Others]: Changing license to LGPL-3.0
### Description

Currently, our mod is using GPL-3.0 as the license. But due to the incompatibility between the license and Minecraft as is pointed out in [GPL's faq](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins), we are considering changing the license to LGPL-3.0, which is compatible with Minecraft.

We value the input and perspectives of our contributors. Please share your thoughts on this proposed license change.. You can either leave a comment below or reply with emoji. We will only perform the change if all our contributors agree on this.

### PR DESCRIPTION
**Pull request by Qubik65536**
### Description/描述

Change the open source license from GPL 3.0 to LGPL 3.0.

### Related Issues/相关的 issue

 

* resolve #32 

### Checklist/清单

- [X] The issues this PR addresses are related to each other/此 PR 解决的 issue 是相关的
- [X] My changes are all related to the related issue above/我的修改都与上方的相关 issue 有关
- [n/a] My changes generate no new warnings/我的修改没有产生新的警告
- [n/a] My code builds and runs on my machine/我的代码在我的电脑上可以编译和运行
- [n/a] I documented my code/我已经为我的代码添加了注释/文档

### Screenshots

n/a

### CODE REVIEW

**Review by zly2006 — CHANGES_REQUESTED** [review]
also change this in fabric.mod.json

**Review by zly2006 — APPROVED** [review]

**Review by wafarm — CHANGES_REQUESTED** [review]
You are using [LGPL-2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html) rather than [LGPL-3.0](https://www.gnu.org/licenses/lgpl+gpl-3.0.txt).

**Comment by Qubik65536** [comment]
> You are using [LGPL-2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html) rather than [LGPL-3.0](https://www.gnu.org/licenses/lgpl+gpl-3.0.txt).

Yeah f**k, it's the GitHub Template, anyway I'll change it later.

**Review by wafarm — APPROVED** [review]

**Comment by Qubik65536** [comment]
This will be merged if I see no objections by Sep. 17, 2023.
/cc @zly2006 @wafarm @lovexyn0827 @onion108 @KikuGie

**Pull request merged**
