### PR TITLE
feat: better runCommand

### PR DESCRIPTION
**Pull request by wafarm**
### Description/描述

A list based runCommand implementation.

### Checklist/清单

- [x] My changes generate no new warnings/我的修改没有产生新的警告
- [x] My code builds and runs on my machine/我的代码在我的电脑上可以编译和运行
- [x] I documented my code/我已经为我的代码添加了注释/文档

### Screenshots

image

### CODE REVIEW

**Review by Qubik65536 — CHANGES_REQUESTED** [review]
I'm not really the one who should review the code, but it looks great from a user point of view.

Except probably fix this:

image

and similar hover text missings.

Or we could wait till we hands directly on the i18n? @zly2006 (and some i18n related discussion in #29 )

**Comment by wafarm** [comment]
Actually, it's a common issue with all masa mods using lists since the translation keys (or similar ones) didn't exist in the language files in malilib. If we are to fix this, then should we add the translation for the original malilib or just creating them in our own namespace (like `reden.widget.hover.add`) ?

**Comment by zly2006** [comment]
I think we have no need to fix this translation issue because the icon is clear enough to let our users know what this button is used for.

I prefer to PR in malilib than use our own translation.

**Review by zly2006 — APPROVED** [review]

**Review by Qubik65536 — APPROVED** [review]
Got it, let's leave it like this for now, it's indeed better that the i18n issue can be fixed on malilib side.

Let's continue our own i18n related discussion in #29

**Pull request merged**
